### ISSUE TITLE
Migrate to the lastest version of Eclipse RCP

### ISSUE THREAD

**Issue by brunogautier** [christophefondacci/nextep-designer#13]
The latest version of Eclipse for RCP and RAP Developers, code name _Oxygen_, is scheduled for the month of June 2017.

The latest maintenance build can be downloaded from [Eclipse Oxygen Releases](http://www.eclipse.org/downloads/packages/release/Oxygen)

**Comment by christophefondacci** [comment]
Good point that Oxygen is not released until June 2017. The issue I had with synchronization seem to be caused by the beta. Everything works fine with current 4.6 Neon release.

Feature has been updated to package Eclipse 4.6 changes so we should be able to push this to the update site to upgrade everyone.
